// Code generated by mockery v2.24.0. DO NOT EDIT.

package mocks

import (
	amqp091 "github.com/rabbitmq/amqp091-go"
	mock "github.com/stretchr/testify/mock"
)

// AmqpService is an autogenerated mock type for the AmqpService type
type AmqpService struct {
	mock.Mock
}

// Clean provides a mock function with given fields:
func (_m *AmqpService) Clean() {
	_m.Called()
}

// PublishMessage provides a mock function with given fields: msg, queue
func (_m *AmqpService) PublishMessage(msg []byte, queue string) error {
	ret := _m.Called(msg, queue)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, string) error); ok {
		r0 = rf(msg, queue)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubscribeToQueue provides a mock function with given fields: queue
func (_m *AmqpService) SubscribeToQueue(queue string) <-chan amqp091.Delivery {
	ret := _m.Called(queue)

	var r0 <-chan amqp091.Delivery
	if rf, ok := ret.Get(0).(func(string) <-chan amqp091.Delivery); ok {
		r0 = rf(queue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan amqp091.Delivery)
		}
	}

	return r0
}

type mockConstructorTestingTNewAmqpService interface {
	mock.TestingT
	Cleanup(func())
}

// NewAmqpService creates a new instance of AmqpService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAmqpService(t mockConstructorTestingTNewAmqpService) *AmqpService {
	mock := &AmqpService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
