// Code generated by mockery v2.24.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ConsumerService is an autogenerated mock type for the ConsumerService type
type ConsumerService struct {
	mock.Mock
}

// Clean provides a mock function with given fields:
func (_m *ConsumerService) Clean() {
	_m.Called()
}

// SubscribeToQueue provides a mock function with given fields: queue
func (_m *ConsumerService) SubscribeToQueue(queue string) {
	_m.Called(queue)
}

type mockConstructorTestingTNewConsumerService interface {
	mock.TestingT
	Cleanup(func())
}

// NewConsumerService creates a new instance of ConsumerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConsumerService(t mockConstructorTestingTNewConsumerService) *ConsumerService {
	mock := &ConsumerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
