// Code generated by mockery v2.24.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// queueSubscriber is an autogenerated mock type for the queueSubscriber type
type queueSubscriber struct {
	mock.Mock
}

// SubscribeToQueue provides a mock function with given fields: queue
func (_m *queueSubscriber) SubscribeToQueue(queue string) {
	_m.Called(queue)
}

type mockConstructorTestingTnewQueueSubscriber interface {
	mock.TestingT
	Cleanup(func())
}

// newQueueSubscriber creates a new instance of queueSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newQueueSubscriber(t mockConstructorTestingTnewQueueSubscriber) *queueSubscriber {
	mock := &queueSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
