// Code generated by mockery v2.24.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// serviceCleaner is an autogenerated mock type for the serviceCleaner type
type serviceCleaner struct {
	mock.Mock
}

// Clean provides a mock function with given fields:
func (_m *serviceCleaner) Clean() {
	_m.Called()
}

type mockConstructorTestingTnewServiceCleaner interface {
	mock.TestingT
	Cleanup(func())
}

// newServiceCleaner creates a new instance of serviceCleaner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newServiceCleaner(t mockConstructorTestingTnewServiceCleaner) *serviceCleaner {
	mock := &serviceCleaner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
