// Code generated by mockery v2.24.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StockService is an autogenerated mock type for the StockService type
type StockService struct {
	mock.Mock
}

// Clean provides a mock function with given fields:
func (_m *StockService) Clean() {
	_m.Called()
}

// SubscribeToQueue provides a mock function with given fields: queue
func (_m *StockService) SubscribeToQueue(queue string) {
	_m.Called(queue)
}

type mockConstructorTestingTNewStockService interface {
	mock.TestingT
	Cleanup(func())
}

// NewStockService creates a new instance of StockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStockService(t mockConstructorTestingTNewStockService) *StockService {
	mock := &StockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
