// Code generated by mockery v2.24.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// cacheSetter is an autogenerated mock type for the cacheSetter type
type cacheSetter struct {
	mock.Mock
}

// StoreChatMessage provides a mock function with given fields: message, room
func (_m *cacheSetter) StoreChatMessage(message []byte, room string) {
	_m.Called(message, room)
}

type mockConstructorTestingTnewCacheSetter interface {
	mock.TestingT
	Cleanup(func())
}

// newCacheSetter creates a new instance of cacheSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newCacheSetter(t mockConstructorTestingTnewCacheSetter) *cacheSetter {
	mock := &cacheSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
